### PR TITLE
Build libunwind instead of a dummy one.

### PR DESCRIPTION
**Pull request by DanielKristofKiss**
libunwind is a perquisite to have exceptions for example.

### CODE REVIEW

**Comment by mplatings** [comment]
We're not planning to support features like exceptions so we've decided to leave libunwind disabled.

**Comment by mplatings** [comment]
> We're not planning to support features like exceptions
This isn't quite right. We don't have any immediate plans to build library variants with exception support, but that doesn't mean this pull request shouldn't be accepted.

**Comment by mplatings** [comment]
The updated change is failing to build:

> clang -cc1as: error: unknown target triple 'x86_64-unknown-linux-gnu', please use -triple or -arch

**Comment by DanielKristofKiss** [comment]
@mplatings it built for me with todays ToT llvm.

**Comment by mplatings** [comment]
I'm not sure why the build succeeded for you. I dug in deeper and it turned out that .S files weren't building because CMAKE_ASM_FLAGS wasn't specified. I pushed a fix for that.
The smoke tests are currently failing for me so I'm going to investigate that before returning to this.

**Pull request merged**
