### PR TITLE
Picolibc tests enabled for armv8*

### PR DESCRIPTION
**Pull request by pwprzybyla**

### CODE REVIEW

**Comment by mplatings** [comment]
Great to see progress on this.
* Can you explain in the commit message what you're changing and why?
* Please avoid unnecessary whitespace changes.

**Comment by pwprzybyla** [comment]
While investigating HardFault's with picolibc tests for armv8* variants. I have discovered that leaving default picolibc values in terms of RAM resolves most of the HardFaults with tests. Only few platforms require increased flash space.

**Comment by mplatings** [comment]
I gave this a try and check-picolibc_aarch64 seems pretty broken

**Comment by pwprzybyla** [comment]
> 

Aarch64 is disabled again as it was. All tests in bundle check-picolibc pass.

**Pull request merged**
