### PR TITLE
Add llvm-strings to the distribution

### PR DESCRIPTION
**Pull request by ostannard**

### CODE REVIEW

**Review by voltur01 — APPROVED** [review]
LGTM

**Comment by voltur01** [comment]
@ostannard would you please cherry-pick into the `llvm-19` branch as well, thank you!

**Comment by ostannard** [comment]
@voltur01 sure, do you think #512 should be cherry-picked too?

**Comment by voltur01** [comment]
Yes, please, to be consistent, thank you!

**Comment by ostannard** [comment]
Cherry-pick: #513

**Pull request merged**
